name: Compile Examples

on:
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "avr/libraries/**"
      - "avr/cores/**"
      - "avr/variants/**"
      - "avr/*.txt"
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "avr/libraries/**"
      - "avr/cores/**"
      - "avr/variants/**"
      - "avr/*.txt"
  # workflow_dispatch event allows the workflow to be triggered manually
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  # repository_dispatch event allows the workflow to be triggered via the GitHub API
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:

jobs:
  compile-examples:
    runs-on: ubuntu-latest

    env:
      platform-name: ATTinyCore:avr

      available-flash-2kB-sketch-paths: |
        - avr/extras/ci/test_sketches_2k/basic_test
      available-flash-4kB-sketch-paths: |
        - avr/libraries/EEPROM/examples/eeprom_crc
        - avr/libraries/EEPROM/examples/eeprom_put
        - avr/libraries/EEPROM/examples/eeprom_read
        - avr/libraries/Wire/examples/digital_potentiometer
        # - avr/libraries/megaTinyCore/examples/ModernRevSer
        - avr/libraries/SoftwareSerial/examples/SoftwareSerialExample
        - avr/libraries/tinyNeoPixel/examples/buttoncycler
        - avr/libraries/tinyNeoPixel/examples/simple
        - avr/libraries/tinyNeoPixel/examples/strandtest
        - avr/libraries/tinyNeoPixel_Static/examples/buttoncycler
        - avr/libraries/tinyNeoPixel_Static/examples/strandtest
        # - avr/extras/ci/test_sketches_4k/serial_test
      available-flash-8kB-sketch-paths: |
        - avr/libraries/SPI/examples/BarometricPressureSensor
        - avr/libraries/SoftwareSerial/examples/TwoPortReceive
        - avr/libraries/Wire/examples/SFRRanger_reader
        - avr/libraries/tinyNeoPixel/examples/RGBWstrandtest
        # - avr/extras/CompileTestSketches/test_analog_read

    strategy:
      fail-fast: false

      matrix:
        device:
          - name: attinyx4:chip=84
            available-flash-kB: 8
          # - name: attinyx4:chip=84
          #   available-flash-kB: 8
          # - name: attinyx4:chip=44
          #   available-flash-kB: 4
          # - name: attinyx4:chip=24
          #   available-flash-kB: 2
          # - name: attinyx41:chip=841
          #   available-flash-kB: 8
          # - name: attinyx41:chip=441
          #   available-flash-kB: 4
          # - name: attinyx5:chip=85
          #   available-flash-kB: 8
          # - name: attinyx5:chip=45
          #   available-flash-kB: 4
          # - name: attinyx5:chip=25
          #   available-flash-kB: 2
          # - name: attinyx61:chip=861
          #   available-flash-kB: 8
          # - name: attinyx61:chip=461
          #   available-flash-kB: 4
          # - name: attinyx61:chip=261
          #   available-flash-kB: 2
          # - name: attinyx7:chip=167
          #   available-flash-kB: 16
          # - name: attinyx7:chip=87
          #   available-flash-kB: 8
          # - name: attinyx8:chip=88
          #   available-flash-kB: 8
          # - name: attinyx8:chip=48
          #   available-flash-kB: 4
          # - name: attiny1634
          #   available-flash-kB: 16
          # - name: attinyx313:chip=4313
          #   available-flash-kB: 4
          # - name: attinyx313:chip=2313a
          #   available-flash-kB: 2
          # - name: attiny828
          #   available-flash-kB: 8
          # - name: attiny43u
          #   available-flash-kB: 4
          # - name: attiny26
          #   available-flash-kB: 2
        soft-serial:
          - ""
          - softserial=enable
          - softserial=txonly

        # Filter out these matrix combinations
        exclude:
          # - soft-serial: softserial=enable
          #   device:
          #     - name: attinyx41:chip=841
          #       available-flash-kB: 8
          # - soft-serial: softserial=txonly
          #   device:
          #     - name: attinyx41:chip=841
          #       available-flash-kB: 8
          # - soft-serial: softserial=enable
          #   device:
          #     - name: attinyx41:chip=441
          #       available-flash-kB: 4
          # - soft-serial: softserial=txonly
          #   device:
          #     - name: attinyx41:chip=441
          #       available-flash-kB: 4
          # - soft-serial: softserial=enable
          #   device:
          #     - name: attinyx7:chip=167
          #       available-flash-kB: 16
          # - soft-serial: softserial=txonly
          #   device:
          #     - name: attinyx7:chip=167
          #       available-flash-kB: 16
          # - soft-serial: softserial=enable
          #   device:
          #     - name: attinyx7:chip=87
          #       available-flash-kB: 8
          # - soft-serial: softserial=txonly
          #   device:
          #     - name: attinyx7:chip=87
          #       available-flash-kB: 8
          # - soft-serial: softserial=enable
          #   device:
          #     - name: attinyx313:chip=4313
          #       available-flash-kB: 4
          # - soft-serial: softserial=txonly
          #   device:
          #     - name: attinyx313:chip=4313
          #       available-flash-kB: 4
          # - soft-serial: softserial=enable
          #   device:
          #     - name: attinyx313:chip=2313a
          #       available-flash-kB: 2
          # - soft-serial: softserial=txonly
          #   device:
          #     - name: attinyx313:chip=2313a
          #       available-flash-kB: 2
          # - soft-serial: softserial=enable
          #   device:
          #     - name: attiny1634
          #       available-flash-kB: 16
          # - soft-serial: softserial=txonly
          #   device:
          #     - name: attiny1634
          #       available-flash-kB: 16
          # - soft-serial: softserial=enable
          #   device:
          #     - name: attiny828
          #       available-flash-kB: 8
          # - soft-serial: softserial=txonly
          #   device:
          #     - name: attiny828
          #       available-flash-kB: 8
          # - soft-serial: ""
          - device:
            - name: attinyx4:chip=84
              available-flash-kB: 8
          # - soft-serial: ""
          #   device:
          #     - name: attinyx4:chip=44
          #       available-flash-kB: 4
          # - soft-serial: ""
          #   device:
          #     - name: attinyx4:chip=24
          #       available-flash-kB: 2
          # - soft-serial: ""
          #   device:
          #     - name: attinyx5:chip=85
          #       available-flash-kB: 8
          # - soft-serial: ""
          #   device:
          #     - name: attinyx5:chip=45
          #       available-flash-kB: 4
          # - soft-serial: ""
          #   device:
          #     - name: attinyx5:chip=25
          #       available-flash-kB: 2
          # - soft-serial: ""
          #   device:
          #     - name: attinyx61:chip=861
          #       available-flash-kB: 8
          # - soft-serial: ""
          #   device:
          #     - name: attinyx61:chip=461
          #       available-flash-kB: 4
          # - soft-serial: ""
          #   device:
          #     - name: attinyx61:chip=261
          #       available-flash-kB: 2
          # - soft-serial: ""
          #   device:
          #     - name: attinyx8:chip=88
          #       available-flash-kB: 8
          # - soft-serial: ""
          #   device:
          #     - name: attinyx8:chip=48
          #       available-flash-kB: 4
          # - soft-serial: ""
          #   device:
          #     - name: attiny43u
          #       available-flash-kB: 4
          # - soft-serial: ""
          #   device:
          #     - name: attiny26
          #       available-flash-kB: 2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Build sketch-paths >= 8kb
      #   if: ${{ matrix.device.available-flash-kB >= 8 }}
      #   env:
      #     job_sketch_paths: |
      #       ${{ env.available-flash-8kB-sketch-paths }}
      #       ${{ env.available-flash-4kB-sketch-paths }}
      #       ${{ env.available-flash-2kB-sketch-paths }}
      #   run: >
      #     echo "sketch paths: $job_sketch_paths"

      # - name: Build sketch-paths == 4kb
      #   if: ${{ matrix.device.available-flash-kB == 4}}
      #   env:
      #     job_sketch_paths: |
      #       ${{ env.available-flash-4kB-sketch-paths }}
      #       ${{ env.available-flash-2kB-sketch-paths }}
      #   run: >
      #     echo "sketch paths: $job_sketch_paths"

      # - name: Build sketch-paths == 2kb
      #   if: ${{ matrix.device.available-flash-kB == 2 }}
      #   env:
      #     job_sketch_paths: |
      #       ${{ env.available-flash-2kB-sketch-paths }}
      #   run: >
      #     echo "sketch paths: $job_sketch_paths"

      - name: Build fqbn with soft serial
        if: ${{ matrix.soft-serial != 0 }}
        run: |
          export job_fqbn=${{ env.platform-name }}:${{ matrix.device.name }},clock=internal_8m,${{ matrix.soft-serial }}
          echo "job_fqbn=$job_fqbn" >> $GITHUB_ENV

      - name: Build fqbn without soft serial
        if: ${{ matrix.soft-serial == 0}}
        run: |
          export job_fqbn=${{ env.platform-name }}:${{ matrix.device.name }},clock=internal_8m
          echo "job_fqbn=$job_fqbn" >> $GITHUB_ENV

      - name: Debug matrix
        run: >
          echo "matrix: ${{ toJson(matrix) }}"

      # See: https://github.com/arduino/compile-sketches/README.md
      - name: Compile examples >= 8kb
        if: ${{ matrix.device.available-flash-kB >= 8 }}
        uses: arduino/compile-sketches@main
        with:
          fqbn: ${{ env.job_fqbn }}
          sketch-paths: |
            ${{ env.available-flash-8kB-sketch-paths }}
            ${{ env.available-flash-4kB-sketch-paths }}
            ${{ env.available-flash-2kB-sketch-paths }}
          platforms: |
            # Install ATTinyCore via Boards Manager for the toolchain
            - source-url: http://drazzy.com/package_drazzy.com_index.json
              name: ${{ env.platform-name }}
            # Overwrite the ATTinyCore release version with the platform from the local path
            - source-path: avr
              name: ${{ env.platform-name }}
          libraries: |
            # The sketches don't have any external library dependencies, so just define an empty array
            -
          verbose: false
          enable-deltas-report: true
          enable-warnings-report: true
          sketches-report-path: sketches-reports

      - name: Compile examples == 4kb
        if: ${{ matrix.device.available-flash-kB == 4 }}
        uses: arduino/compile-sketches@main
        with:
          fqbn: ${{ env.job_fqbn }}
          sketch-paths: |
            ${{ env.available-flash-4kB-sketch-paths }}
            ${{ env.available-flash-2kB-sketch-paths }}
          platforms: |
            # Install ATTinyCore via Boards Manager for the toolchain
            - source-url: http://drazzy.com/package_drazzy.com_index.json
              name: ${{ env.platform-name }}
            # Overwrite the ATTinyCore release version with the platform from the local path
            - source-path: avr
              name: ${{ env.platform-name }}
          libraries: |
            # The sketches don't have any external library dependencies, so just define an empty array
            -
          verbose: false
          enable-deltas-report: true
          enable-warnings-report: true
          sketches-report-path: sketches-reports

      - name: Compile examples == 2kb
        if: ${{ matrix.device.available-flash-kB == 2 }}
        uses: arduino/compile-sketches@main
        with:
          fqbn: ${{ env.job_fqbn }}
          sketch-paths: |
            ${{ env.available-flash-2kB-sketch-paths }}
          platforms: |
            # Install ATTinyCore via Boards Manager for the toolchain
            - source-url: http://drazzy.com/package_drazzy.com_index.json
              name: ${{ env.platform-name }}
            # Overwrite the ATTinyCore release version with the platform from the local path
            - source-path: avr
              name: ${{ env.platform-name }}
          libraries: |
            # The sketches don't have any external library dependencies, so just define an empty array
            -
          verbose: false
          enable-deltas-report: true
          enable-warnings-report: true
          sketches-report-path: sketches-reports
